version: "3.1"
services:
    server:
        build: ./server
        image: easyappointments-server:v1
        container_name: easyappointments-server
        ports:
            - "8000:80"
        volumes:
            - ../:/var/www/html
            - ./server/php.ini:/usr/local/etc/php/conf.d/99-overrides.ini
